### ISSUE TITLE
PCB in Gerber format & BOM

### ISSUE THREAD

**Issue by knightron0** [teco-kit/open-earable#13]
I'm trying to develop this device for testing a research project I'm working on -- is it possible to get the PCB designs in the Gerber format? It's hard to produce the exact spec from the PDF files. A comprehensive bill of materials (BOM) would be great too.

Let me know if any of this is possible!

**Comment by TobiasRoeddiger** [comment]
Thanks for the comment. I've updated the website :)

https://open-earable.teco.edu/
